dist: xenial
language: node_js
node_js:
  <% nodeVersions.forEach(function(version){ -%>
    - <%= version %>
  <% }); %>
cache:
  directories:
    - node_modules

branches:
  except:
  - "/^renovate\\/.+$/"

<% if (type === 'mono')  { -%>
# We need to use yarn to use lerna #yakshaving
install:
  - yarn global add lerna
  - yarn
script:
  yarn test
<% } %>
